import Sidebar from "../sidebar";
import type { Metadata } from "next";
import "../globals.css";
import LeftbarWriter from "../component/leftbar";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-screen min-h-screen  flex pt-9  overflow-auto flex-col pb-0 md:pb-0  items-center justify-center bg-[url(/dashboard.png)]">
      <Sidebar />
      <div className="flex  md:flex-row-reverse  flex-col min-h-full w-full p-4  md:pb-4 pb-0   text-white items-center   md:gap-2 gap-50  ">
        {children} <LeftbarWriter role={"reader"} />
      </div>
    </div>
  );
}
